{{- if .Values.spire.oidcDiscoveryProvider.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spire-spiffe-oidc-discovery-provider
  namespace: {{ .Release.Namespace }}
  annotations:
    route.openshift.io/termination: {{ .Values.spire.oidcDiscoveryProvider.ingress.termination }}
spec:
  rules:
    - host: {{ tpl .Values.spire.oidcDiscoveryProvider.ingress.host $ }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.spire.oidcDiscoveryProvider.service.name }}
                port:
                  number: {{ .Values.spire.oidcDiscoveryProvider.service.port }}
{{- end }}