{{- if and (eq .Values.keycloak.ingress.enabled true) (eq .Values.keycloak.tls.serviceServing true) }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.keycloak.tls.secret | quote }}  
  labels:
    app: {{ .Values.keycloak.name }}
    app.kubernetes.io/instance: {{ .Values.keycloak.name }}
  name: {{ include "keycloak.service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
  selector:
    app: {{ .Values.keycloak.name }}
    app.kubernetes.io/instance: {{ .Values.keycloak.name }}
{{- end }}
