apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  db:
    host: postgresql-db
    passwordSecret:
      key: password
      name: postgresql-db
    usernameSecret:
      key: username
      name: postgresql-db
    vendor: postgres
  hostname:
    hostname: {{ include "keycloak.ingress.hostname" . }}
  http:
    tlsSecret: {{ .Values.keycloak.tls.secret }}
  ingress:
    {{- if not (eq .Values.keycloak.ingress.enabled true) }}
    enabled: false
    {{- end }}
  instances: 1
