global:
  localClusterDomain: apps.example.com

keycloak:
  name: keycloak

  ingress:
    enabled: true
    service: keycloak-service-trusted
    termination: reencrypt
    hostname: ""
  
  tls:
    serviceServing: true
    secret: keycloak-tls
