apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: {{ .Values.compliance.scanSettingBinding.name }}
  namespace: openshift-compliance
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
  labels:
    app.kubernetes.io/component: compliance-scan-binding
settingsRef:
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1
  name: {{ .Values.compliance.scanSetting.name }}
# Profiles to bind to this scan setting
profiles:
  - name: {{ .Values.compliance.scanSettingBinding.profile }}
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1

