apiVersion: v1
kind: ConfigMap
metadata:
  name: qtodo-config-env
  namespace: {{ .Release.Namespace }}
data:
{{- if eq .Values.app.oidc.enabled true }}
  QUARKUS_OIDC_ENABLED: "{{ .Values.app.oidc.enabled }}"
  QUARKUS_OIDC_AUTH_SERVER_URL: "{{ default (printf "https://keycloak.%s/realms/ztvp" .Values.global.localClusterDomain) .Values.app.oidc.authServerUrl }}"
  QUARKUS_OIDC_CLIENT_ID: "{{ .Values.app.oidc.clientId }}"
  QUARKUS_OIDC_APPLICATION_TYPE: "{{ .Values.app.oidc.applicationType }}"
  QUARKUS_HTTP_AUTH_PERMISSION_AUTHENTICATED_PATHS: "{{ .Values.app.oidc.authenticatedPaths }}"
  QUARKUS_HTTP_AUTH_PERMISSION_AUTHENTICATED_POLICY: "{{ .Values.app.oidc.authenticatedPolicy }}"
  QUARKUS_OIDC_AUTHENTICATION_FORCE_REDIRECT_HTTPS_SCHEME: "true"
{{- end }}
