apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  labels:
    app: qtodo
  name: qtodo
  namespace: qtodo
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: qtodo
  sessionAffinity: None
  type: ClusterIP