apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  labels:
    app: qtodo-db
  name: qtodo-db
  namespace: qtodo
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: qtodo-db
  sessionAffinity: None
  type: ClusterIP

