# Default values for qtodo

# QTodo application configuration
app:
  name: qtodo

# PostgreSQL database configuration
postgresql:
  name: qtodo-db

  # Database configuration
  auth:
    database: tasks
    username: qtodo_user
    # This is intentionally included here as an antipattern to be addressed
    password: RedH@tPassw0rd
  

  

