# Default values for qtodo
global:
  localClusterDomain: apps.example.com
  secretStore:
    name: "vault-backend"
    kind: "ClusterSecretStore"

# QTodo application configuration
app:
  name: qtodo

  oidc:
    enabled: false
    authServerUrl: ""
    clientId: qtodo-app
    clientSecret: ""
    applicationType: "web-app"
    authenticatedPaths: "/*"
    authenticatedPolicy: "authenticated"

# PostgreSQL database configuration
postgresql:
  name: qtodo-db

  # Database configuration
  auth:
    secretName: qtodo-db-secret
    database: tasks
    username: qtodo_user
    passwordVaultKey: secret/data/global/qtodo
